const { GoogleSpreadsheet } = require('google-spreadsheet');

// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet('1sc0y5jkHPlqzS5z1oEjLXYdBWs9lw2yiDlikVow9Q8U');

(async function() {

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: "sheets@robomatrix-ucb.iam.gserviceaccount.com",
      private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDG7L1WU3w4PEKd\npbcOlYM8+GrZ3zuVvzwG7M8lWrz166+pegcAAE4RjSk7wuVhFxx4SATuO0seTI9n\nmrOpGXvaI1pDkJhPXd1a7wFGciM6xstQybgDZh1Toa9v4/2DmFByZMTSmQLxFo56\nZEc4Hk0oL9fG7V2lGrQ6tgC7i+dRVxrkduNytwnWJC1s/SFsj7u9VRrJ9+LQmxJa\nlIkDXF7OkTlNPRsrIS3pUXvaytxxRbyIDJ/ZZh2JUNs6bv53kpCxp/NUDjFbagcg\n+sdAHENjmX4P9Dw6VrHHR2hugr4zn/zExMA6/JQawKICwPAYAosRAQpZ41T3YCgk\naTzSfchhAgMBAAECggEAJk6brX6ZOskb+PjbFiNjqP+bsAYlltJDUIAU6fgd0GvJ\nIaVeqLjmT8nzyU7gVkCZmm4gCPKBJj4PFZ/8fhFqwNiy/rTfJ9WHFYZWJAdB0oVK\nzO1zkq/88Mh/nNf2T3uq7kSKhJWzs9KosFgUQPHQ4O7JqkS2ll9cmrvGy1cHPinl\nj9hg2DLZrPNQinXe9j18GAbkPo6kuWTvQlq+eC2KmZHbOdoL8At3edeyeWYrdxc0\nhlUU1kPrEQF8ecbGNNrJlHAcuQxZuWIF8jI8jIoSccSNEvWYahjGu9k8F9m/kXCU\n1kMSzGipMCey/mavW/k2hqJxbXqYvFluGcwXb4G32QKBgQDoWNcA+HcuGhA58v66\ny1wJGDycOsWLOZZVk2q3Z7TBkhzuIxnDT93VysoUBtK30C+gpNIKxklVjys3aIko\n9mS2/Aqdek+39hkDB/BMBZlxteaa7ZcoShxz3iZZe+xCweRqO8aohErKonAW+JnY\nQ4gjjf+lIJLEsRfj4N/on4iZNQKBgQDbLOMfscjKhwD8O90/XetjGWMDk2M+BUV+\nEA40fxBGwEiqd4cjCK6RQ7JZ+15zU+FYwrC++a5BKw1CJRl9HMqcLAVukvW+a0Zr\nvJ8KLXxmPCgYE5KhpEdUKQFqcvYTCU4nBUHH2A2XrOTrwQDaAohUYvd+zd4QR9xy\nFPBrgP/D/QKBgQCuOcfnY2lC+apHOe5HNayq6TCx2eQ9lQ4k12kDZFGHgUAOVeXA\nrkfjQ7AqOj+SNBsys8UI7U0aSkQWxV1siO5WxEJVed0DThfNTQukheJdARCOBjD9\nti0FuYQ6P5GXMXtNKcu6m5DVx96TaxE5uNICDz2unfFQapdGel6MOeydLQKBgH/3\nXUSMEKfu2uxqJ2tv8pcRo3Xa//6eJUzNIv4TkfU9HzAoSYZy8zltRRy0XxkGyHOC\neJ+IN+1krYEJGDCsNr+oFCPTOhfLmnoczt6qYA9w4BfulZY6zEqfBmyYYoQK0s6F\nizqbMpR0JdRgA5dGE0Lx5X7rw9PNoTAaeaTK1IohAoGAIL6Iq+bwqMKuEqIMH8Jb\nIBVyi1cPlgPmcX9JmYMkVN2vU1Sj/+oVKPcjl6/v9vLvirErXGrSZoiydqKixH/3\nd6w1OAs1YKVWFuGAmyvfmPvFeubV8kVzGn0FNwgJyXjF9L04UscNo7ampiCJ24MT\nFLROVj8eTDabAzjWWaz3wBk=\n-----END PRIVATE KEY-----\n",
    });
    
    await doc.loadInfo(); // loads document properties and worksheets
    console.log(doc.title);
    await doc.updateProperties({ title: 'renamed doc' });
    
    const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    console.log(sheet.title);
    console.log(sheet.rowCount);
    
    // adding / removing sheets
    const newSheet = await doc.addSheet({ title: 'hot new sheet!' });
    await newSheet.delete();
}());
